<?php

namespace Proxies\__CG__\Lsi\BiblioBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Collection extends \Lsi\BiblioBundle\Entity\Collection implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function addLivre(\Lsi\BiblioBundle\Entity\Livre $livre)
    {
        $this->__load();
        return parent::addLivre($livre);
    }

    public function removeLivre(\Lsi\BiblioBundle\Entity\Livre $livre)
    {
        $this->__load();
        return parent::removeLivre($livre);
    }

    public function getLivre()
    {
        $this->__load();
        return parent::getLivre();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setActiveLivres($livres)
    {
        $this->__load();
        return parent::setActiveLivres($livres);
    }

    public function getActiveLivres()
    {
        $this->__load();
        return parent::getActiveLivres();
    }

    public function setMoreLivres($livres)
    {
        $this->__load();
        return parent::setMoreLivres($livres);
    }

    public function getMoreLivres()
    {
        $this->__load();
        return parent::getMoreLivres();
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'livre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}