<?php

namespace Proxies\__CG__\Lsi\BiblioBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \Lsi\BiblioBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNomComplet($nomComplet)
    {
        $this->__load();
        return parent::setNomComplet($nomComplet);
    }

    public function getNomComplet()
    {
        $this->__load();
        return parent::getNomComplet();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setRole($role)
    {
        $this->__load();
        return parent::setRole($role);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setDateInscription($dateInscription)
    {
        $this->__load();
        return parent::setDateInscription($dateInscription);
    }

    public function getDateInscription()
    {
        $this->__load();
        return parent::getDateInscription();
    }

    public function setUserSuspendu($userSuspendu)
    {
        $this->__load();
        return parent::setUserSuspendu($userSuspendu);
    }

    public function getUserSuspendu()
    {
        $this->__load();
        return parent::getUserSuspendu();
    }

    public function addAvisUserLivre(\Lsi\BiblioBundle\Entity\AvisUserLivre $avisUserLivre)
    {
        $this->__load();
        return parent::addAvisUserLivre($avisUserLivre);
    }

    public function removeAvisUserLivre(\Lsi\BiblioBundle\Entity\AvisUserLivre $avisUserLivre)
    {
        $this->__load();
        return parent::removeAvisUserLivre($avisUserLivre);
    }

    public function getAvisUserLivre()
    {
        $this->__load();
        return parent::getAvisUserLivre();
    }

    public function setDateInscriptionValue()
    {
        $this->__load();
        return parent::setDateInscriptionValue();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nomComplet', 'email', 'password', 'age', 'role', 'dateInscription', 'userSuspendu', 'avis_user_livre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}