parameters:
#    lsi_biblio.example.class: Lsi\BiblioBundle\Example

services:
#    lsi_biblio.example:
#        class: %lsi_biblio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
