<?php

namespace Lsi\BiblioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{
	public function getWithLivres()
	{
		$query = $this->getEntityManager()->createQuery('SELECT c FROM LsiBiblioBundle:Collection c LEFT JOIN c.livre j WHERE j.enLigne = :enLigneVal')->setParameter('enLigneVal',true);
		return $query->getResult();
	}
} 